import { CatalogPromotionProduct } from "./CatalogPromotionProduct";
import { CategoryPath } from "./CategoryPath";
import { CategoryResponse } from "./CategoryResponse";
import { MainAttributeDto } from "./MainAttributeDto";
import { PriceHistory } from "./PriceHistory";
import { ProductAttributeDTO } from "./ProductAttributeDTO";
import { ProductSpecification } from "./ProductSpecification";
import { ProductVarientDTO } from "./ProductVarientDTO";
import { ReviewResponse } from "./ReviewResponse";

export class ProductResponse {
  id!: number;
  productId!: number;
  categoryId!: number;
  categoryName!: string;
  businessId!: number;
  userId!: string;
  barcode!: string;
  brandId!: number;
  brandName!: string;
  description!: string;
  isChildItem!: string;
  productName!: string;
  productTypeStatus!: string;
  productVarientDTOs!: ProductVarientDTO[];
  selfGenProductId!: string;
  price!: number;
  salePrice!: number;
  discount!: number;
  costPrice!: number;
  images!: string[];
  sizeChartImageUrl!: string;
  mainImageUrl!: string;
  productSpecificationDTOS!: ProductSpecification[];
  quantity!: number;
  productDimentions!: string;
  productWeight!: string;
  url!: string;
  isbn!: string;
  upc!: string;
  ean!: string;
  mpn!: string;
  seoTitle!: string;
  keywords!: string;
  seoDescription!: string;
  shoppingCategoryId!: number;
  isShow!: boolean;
  shoppingCategoryPath!: string;
  categoryPath!: CategoryPath[];
  addedToWishlist: boolean = false;
  promotionDiscount! : number;
  promotionId! : number;
  promotionDescription! : string;
  mainAttributeDtos!: MainAttributeDto[];
  priceHistory!: PriceHistory[];
  name!: string;
  categoryL1!: CategoryResponse;
  categoryL2!: CategoryResponse;
  categoryL3!: CategoryResponse;
  cacheQuantity!: number;
  catalogPromotionProductResponses: CatalogPromotionProduct[] = [];
  catalogPromotionProduct!: CatalogPromotionProduct[];
  reviews: ReviewResponse[] = [];
  rating = 0;
  totalResponses!: number;
  reviewCount!: number;
  averageRating!: number;
  averageReview!: number;
  videoUrl!: string;
  productWeights!: number;
  availableQuantity!: number;
  otherSelectedProductAttributes!: ProductAttributeDTO[];
  mainSelectedProductAttributes!: ProductAttributeDTO[];
  packageSizeLength!: number;
  packageSizeWidth!: number;
  packageSizeHeight!: number;
  sizeUnit!: string;
  weightUnit!: string
  variablePrice!: boolean;
  minPrice!: number;
  maxPrice!: number;
  priceVary!: boolean;
  inStock!: boolean;
  returnType: any;
  returnPolicy: any;
  returnFeeType: any;
  returnFee: any;
}
