image: alpine/git:latest

pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        clone:
          enabled: false
        script:
          - git clone --mirror https://x-token-auth:"$BITBUCKET_VARIABLE"@bitbucket.org/fazeal/angularbusinesscustomersite.git
          - cd angularbusinesscustomersite.git
          - git push --mirror https://x-token-auth:"$GITHUB_VARIABLE2"@github.com/Khasaleh/angularbusinesscustomersite.git
        test: false
