FROM node:20.19-alpine as build-step
ENV NODE_ENV=prod
WORKDIR /app


COPY . /app

RUN npm install --force

RUN npm i -g @angular/cli

RUN ng build --c=prod --aot --output-hashing=all

FROM nginx:1.21-alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build-step /app/dist/* /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]